baseURL: "https://plug-world.com/"
title: PlugWorld
theme: PaperMod

enableRobotsTXT: true

params:
  defaultTheme: auto

  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowFullTextinRSS: true
  ShowToc: true

  profilemode:
    enabled: true
    Title: "PlugWorld ðŸ“º"
    subtitle: "I make video games, videos, and tutorials."

  socialIcons:
    - name: youtube
      url: "https://www.youtube.com/c/plugworld"
    - name: itch
      url: "https://plugworldg.itch.io/"
    - name: github
      url: "https://github.com/HelamanWarrior/"
    - name: linkedin
      url: "https://www.linkedin.com/in/parker-anderson-756030214/"
    - name: rss
      url: "posts/index.xml"

menu:
  main:
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 1
    - identifier: games
      name: Games
      url: /games/
      weight: 2
    - identifier: videos
      name: Videos
      url: /videos/
      weight: 3
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 4
